import React, { useState, useEffect } from 'react';
import { jobs as allJobs } from '../data/mockJobs';
import { calculateMatchScore, getScoreColor } from '../utils/scoring';
import Button from './Button';
import { Mail, Copy, RefreshCw, Calendar, MapPin, Briefcase } from 'lucide-react';
import { Link } from 'react-router-dom';

const Digest = () => {
    const [digest, setDigest] = useState(null);
    const [preferences, setPreferences] = useState(null);
    const [loading, setLoading] = useState(true);
    const [generatedDate, setGeneratedDate] = useState(null);

    const today = new Date().toISOString().split('T')[0]; // YYYY-MM-DD
    const storageKey = `jobTrackerDigest_${today}`;

    useEffect(() => {
        // 1. Load Preferences
        const prefs = localStorage.getItem('jobTrackerPreferences');
        if (prefs) setPreferences(JSON.parse(prefs));

        // 2. Check for existing digest
        const savedDigest = localStorage.getItem(storageKey);
        if (savedDigest) {
            setDigest(JSON.parse(savedDigest));
            setGeneratedDate(today);
        }

        setLoading(false);
    }, [storageKey, today]);

    const generateDigest = () => {
        if (!preferences) return;

        setLoading(true);

        // 1. Calculate Scores
        const scoredJobs = allJobs.map(job => ({
            ...job,
            matchScore: calculateMatchScore(job, preferences)
        }));

        // 2. Filter & Sort
        // Filter: Match Score > 0
        const candidates = scoredJobs.filter(j => j.matchScore > 0);

        // Sort: Score DESC, then Date DESC (Newest first)
        candidates.sort((a, b) => {
            if (b.matchScore === a.matchScore) return a.postedDaysAgo - b.postedDaysAgo;
            return b.matchScore - a.matchScore;
        });

        // 3. Slice Top 10
        const top10 = candidates.slice(0, 10);

        // 4. Save
        localStorage.setItem(storageKey, JSON.stringify(top10));
        setDigest(top10);
        setGeneratedDate(today);
        setLoading(false);
    };

    const handleCopy = () => {
        if (!digest) return;
        const text = digest.map(j =>
            `[${j.matchScore}% Match] ${j.title} at ${j.company} - ${j.location}`
        ).join('\n');

        navigator.clipboard.writeText(
            `🚀 Top 10 Jobs for ${today}\n\n${text}\n\nGenerated by Job Tracker`
        );
        alert('Digest copied to clipboard!');
    };

    const handleEmail = () => {
        if (!digest) return;
        const subject = encodeURIComponent(`My Job Digest - ${today}`);
        const body = encodeURIComponent(
            `Here are my top job matches for today:\n\n` +
            digest.map(j =>
                `• ${j.title} at ${j.company} (${j.matchScore}% Match)\n  Location: ${j.location}\n  Link: ${j.applyUrl}`
            ).join('\n\n')
        );
        window.location.href = `mailto:?subject=${subject}&body=${body}`;
    };

    // --- RENDER HELPERS ---

    if (loading) return <div className="p-10 text-center text-secondary">Loading...</div>;

    // State: No Preferences
    if (!preferences) {
        return (
            <div className="flex flex-col items-center justify-center h-[60vh] text-center max-w-md mx-auto">
                <div className="bg-primary/10 p-4 rounded-full mb-4 text-primary">
                    <Mail size={32} />
                </div>
                <h2 className="font-heading text-xl mb-2">Personalize Your Digest</h2>
                <p className="text-secondary mb-6">
                    We need to know what you're looking for to generate your daily top 10 matches.
                </p>
                <Link to="/settings">
                    <Button variant="primary">Set Preferences</Button>
                </Link>
            </div>
        );
    }

    // State: Not Generated Yet
    if (!digest) {
        return (
            <div className="flex flex-col items-center justify-center h-[60vh] text-center max-w-md mx-auto">
                <div className="bg-accent/10 p-4 rounded-full mb-4 text-accent">
                    <RefreshCw size={32} />
                </div>
                <h2 className="font-heading text-xl mb-2">Ready to Generate?</h2>
                <p className="text-secondary mb-6">
                    Create your curated list of the top 10 jobs matching your criteria for <strong>{today}</strong>.
                </p>
                <Button variant="primary" onClick={generateDigest} className="flex items-center gap-2">
                    <RefreshCw size={18} />
                    Generate Today's 9AM Digest (Simulated)
                </Button>
                <p className="text-xs text-secondary mt-4 bg-tertiary px-2 py-1 rounded">
                    Demo Mode: Triggers manually instead of scheduled.
                </p>
            </div>
        );
    }

    // State: Generated (Email View)
    return (
        <div className="digest-container max-w-2xl mx-auto pb-10">
            {/* Action Bar */}
            <div className="flex justify-between items-center mb-6">
                <div className="flex items-center gap-2 text-primary font-bold">
                    <Calendar size={18} />
                    {generatedDate}
                </div>
                <div className="flex gap-2">
                    <Button variant="secondary" onClick={handleCopy} className="flx items-center gap-2 text-xs">
                        <Copy size={16} /> Copy List
                    </Button>
                    <Button variant="secondary" onClick={handleEmail} className="flx items-center gap-2 text-xs">
                        <Mail size={16} /> Email Draft
                    </Button>
                </div>
            </div>

            {/* Email Body */}
            <div className="bg-white border border-border rounded-lg shadow-sm overflow-hidden">
                {/* Email Header */}
                <div className="bg-primary text-white p-8 text-center">
                    <h1 className="font-heading text-2xl mb-2">Top 10 Jobs For You</h1>
                    <p className="opacity-90 text-sm">Your Daily 9AM Digest • {generatedDate}</p>
                </div>

                {/* Content */}
                <div className="p-8">
                    {digest.length === 0 ? (
                        <div className="text-center py-10 text-secondary">
                            No matching roles found today based on your preferences.
                            <br />Check back tomorrow or broaden your criteria.
                        </div>
                    ) : (
                        <div className="space-y-6">
                            {digest.map((job, index) => (
                                <div key={job.id} className="border-b border-border pb-6 last:border-0 last:pb-0">
                                    <div className="flex justify-between items-start mb-2">
                                        <div>
                                            <h3 className="font-bold text-lg text-primary">{index + 1}. {job.title}</h3>
                                            <p className="text-accent font-medium">{job.company}</p>
                                        </div>
                                        <span
                                            className="text-xs font-bold px-2 py-0.5 rounded-full text-white whitespace-nowrap"
                                            style={{ backgroundColor: getScoreColor(job.matchScore) }}
                                        >
                                            {job.matchScore}% Match
                                        </span>
                                    </div>

                                    <div className="flex gap-4 text-xs text-secondary mb-3">
                                        <div className="flex items-center gap-1">
                                            <MapPin size={12} /> {job.location}
                                        </div>
                                        <div className="flex items-center gap-1">
                                            <Briefcase size={12} /> {job.experience}
                                        </div>
                                    </div>

                                    <a
                                        href={job.applyUrl}
                                        target="_blank"
                                        rel="noreferrer"
                                        className="text-sm font-bold text-primary hover:text-accent hover:underline"
                                    >
                                        Apply Now &rarr;
                                    </a>
                                </div>
                            ))}
                        </div>
                    )}
                </div>

                {/* Recent Status Updates Section */}
                <StatusUpdatesSection />

                {/* Footer */}
                <div className="bg-tertiary p-6 text-center text-xs text-secondary border-t border-border">
                    <p>This digest was generated based on your personal preferences.</p>
                    <p className="mt-1">Job Notification Tracker • Premium Build</p>
                </div>
            </div>
        </div>
    );
};

export default Digest;

const StatusUpdatesSection = () => {
    const [updates, setUpdates] = useState([]);

    useEffect(() => {
        const statusData = localStorage.getItem('jobTrackerStatus');
        if (statusData) {
            const parsed = JSON.parse(statusData);
            const list = Object.entries(parsed).map(([id, data]) => {
                const job = allJobs.find(j => j.id === parseInt(id));
                return { ...data, job };
            }).filter(item => item.job)
                .sort((a, b) => new Date(b.date) - new Date(a.date))
                .slice(0, 5);
            setUpdates(list);
        }
    }, []);

    if (updates.length === 0) return null;

    return (
        <div className="border-t border-border p-8 bg-tertiary/30">
            <h3 className="font-heading text-lg mb-4 text-primary">Recent Status Updates</h3>
            <div className="bg-white rounded border border-border overflow-hidden">
                <table className="w-full text-sm text-left">
                    <thead className="bg-tertiary text-secondary font-medium">
                        <tr>
                            <th className="p-3">Job</th>
                            <th className="p-3">Company</th>
                            <th className="p-3">Status</th>
                            <th className="p-3">Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        {updates.map((update, i) => (
                            <tr key={i} className="border-t border-border last:border-0 hover:bg-tertiary/10 transition-colors">
                                <td className="p-3 font-medium text-primary">{update.job.title}</td>
                                <td className="p-3 text-secondary">{update.job.company}</td>
                                <td className="p-3">
                                    <span className={`px-2 py-1 rounded-full text-xs font-bold ${update.status === 'Applied' ? 'bg-blue-100 text-blue-700' :
                                            update.status === 'Selected' ? 'bg-green-100 text-green-700' :
                                                update.status === 'Rejected' ? 'bg-red-100 text-red-700' : 'bg-gray-100 text-gray-700'
                                        }`}>
                                        {update.status}
                                    </span>
                                </td>
                                <td className="p-3 text-secondary text-xs">
                                    {new Date(update.date).toLocaleDateString()}
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>
        </div>
    );
};
